version: "3"
services:
  blst:
    build:
      context: .
      args:
        CI: ${CI}
    volumes:
      - ./build:/workdir/build:rw
      - ./blst:/workdir/blst:ro
      - ./proof:/workdir/proof:ro
      - ./spec:/workdir/spec:ro
      - ./tests:/workdir/tests:ro
      - ./scripts:/workdir/scripts:ro
