version: "3"
services:
  blst:
    build: .
    volumes:
      - ./build:/workdir/build:rw
      - ./blst:/workdir/blst:ro
      - ./blst_recent:/workdir/blst_recent:ro
      - ./blst_bulk_addition:/workdir/blst_bulk_addition:ro
      - ./cryptol-specs:/workdir/cryptol-specs:ro
      - ./proof:/workdir/proof:rw
      - ./spec:/workdir/spec:rw
      - ./tests:/workdir/tests:ro
      - ./scripts:/workdir/scripts:ro
      - ./patches:/workdir/patches:ro
