version: "3"
services:
  blst:
    build: .
    volumes:
      - ./build:/workdir/build:rw
      - ./blst:/workdir/blst:ro
      - ./blst_patched:/workdir/blst_patched:ro
      - ./cryptol-specs:/workdir/cryptol-specs:ro
      - ./proof:/workdir/proof:ro
      - ./spec:/workdir/spec:ro
      - ./tests:/workdir/tests:ro
      - ./scripts:/workdir/scripts:ro
      - ./patches:/workdir/patches:ro
