name: Proofs
on: [pull_request]

jobs:
  proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker-compose pull
      - run: docker-compose build
      - run: docker-compose run blst
      - run: |
          curl -sSLo zola.tar.gz "https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz"
          tar -xzf zola.tar.gz
          printf '\nY\nY\nY\n' | ./zola init -f pages
          sed -i '1s/^/theme = "docsascode"\ntitle = "Proof Summaries"\n/' pages/config.toml
          git clone --depth 1 "https://github.com/codeandmedia/zola_docsascode_theme" pages/themes/docsascode
          for p in build/*_output; do
            cat <(printf '+++\n%s\n%s\n+++\n' "title = \"$(basename $p)\"" "date = $(date -I)") $p > pages/content/$(basename $p).md
          done
          cd pages && ../zola build -u "https://galoisinc.github.io/blst-verification"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages/public
