name: Proofs
on: [pull_request]

jobs:
  proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker-compose pull
      - run: docker-compose build
        # will be unnecessary once saw has a commandline flag for this
      - run: |
          for p in proof/{hash_to_field,keygen,memory_safety}.saw; do
            {
              echo
              echo "enable_experimental;"
              echo "summarize_verification;"
            } >> "$p"
          done
      - run: docker-compose run blst
      - run: |
          sudo chown -R $USER:$(id -gn $USER) build
          sed -i -n '/^# LLVM Functions Analyzed$/,$p' build/*_output
      - run: |
          curl -sSLo zola.tar.gz "https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz"
          tar -xzf zola.tar.gz
          printf '\nY\nY\nY\n' | ./zola init -f pages
          sed -i '1s/^/theme = "docsascode"\ntitle = "Proof Summaries"\n/' pages/config.toml
          git clone --depth 1 "https://github.com/codeandmedia/zola_docsascode_theme" pages/themes/docsascode
          for p in build/*_output; do
            cat <(printf '+++\n%s\n%s\n+++\n' "title = \"$(basename $p)\"" "date = $(date -I)") $p > pages/content/$(basename $p).md
          done
          cd pages && ../zola build -u "https://${{ github.repository_owner }}.github.io/${GITHUB_REPOSITORY#*/}"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages/public
      # - name: "Post Summary on PR"
      #   uses: actions/github-script@v3
      #   if: github.event_name == 'pull_request'
      #   with:
      #     script: |
      #       const fs = require('fs'), d = `${process.env.GITHUB_WORKSPACE}/build`;
      #       const body = fs.readdirSync(d).filter(f => f.endsWith('_output')).map(f => fs.readFileSync(`${d}/${f}`).toString()).join();
      #       await github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: body
      #       });
      #
      #       // Doesn't actually work yet
      #       const opts = github.issues.listComments.endpoints.merge({ owner, repo, issue_number });
      #       for await (const c of github.paginate.iterator(opts)) {
      #         console.log(JSON.stringify(c,null,2));
      #       }
