name: Proofs
on: [pull_request]

jobs:
  proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker-compose pull
      - run: docker-compose build
      - run: docker-compose run blst
